[package]
name = "server"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
