services: docker

language: crystal

env:
  matrix:
    - "TESTLANG=crystal"
    - "TESTLANG=ruby"
    - "TESTLANG=nim"
    - "TESTLANG=python"
    - "TESTLANG=go"
    - "TESTLANG=swift"
    - "TESTLANG=rust"
    - "TESTLANG=node"
    - "TESTLANG=elixir"
    - "TESTLANG=cpp"
    - "TESTLANG=scala"
    - "TESTLANG=csharp"
    - "TESTLANG=java"
    - "TESTLANG=php"

script:
  - shards build
  - make ${TESTLANG}
  - bin/benchmarker ${TESTLANG} --check
