services: docker
language: crystal
before_install: pip install yamllint --user
install: shards build --release

env:
  matrix:
    - "TESTLANG=crystal"
    - "TESTLANG=ruby"
    - "TESTLANG=nim"
    - "TESTLANG=python"
    - "TESTLANG=go"
    - "TESTLANG=swift"
    - "TESTLANG=rust"
    - "TESTLANG=node"
    - "TESTLANG=elixir"
    - "TESTLANG=cpp"
    - "TESTLANG=scala"
    - "TESTLANG=csharp"

script:
  - crystal spec
  - bin/ameba tools
  - bin/ameba crystal/*
  - yamllint shard.yml
  - yamllint neph.yaml
  - yamllint .travis.yml
  - make ${TESTLANG}
  - bin/benchmarker ${TESTLANG} -r 1
